### ISSUE TITLE
Range - zbiorczo

### ISSUE THREAD

**Issue by LIttleAncientForestKami** [pi0trk/numberGuessingGame#11]
By przyspieszyć:

1. :+1: za fajny komunikat błędu
2. :-1: za rzucanie wyjątku a nie poprawienie go i pójście dalej, szkoda Ci dwu linijek kodu czy jak?
3. :-1: za rodzaj rzucanego wyjątku
4. :-1: za komentarze techniczne na polach - takie coś w Jawadoku by się mogło i powinno znaleźć a nie w technicznym komciu
5. :+1: za toString, byłby dodatkowy plus jakbyś użył tam `String.format` bo byłoby czytelniej niż 4krotna konkatenacja
6. :+1: za drawRange które losuje nie od 0 do sufitu ale uwzględnia podłogę, szkoda, że nie pomyślałeś jak to wylosować nawet jeśli masz sufit == podłoga - Twój if jest zbędny
7. :+1: za liczbę w zasięgu
8. :-1: za wykluczenie sufitu z losowania a traktowanie go w toString i w liczbie w zasięgu jakby był NIEwykluczony (zwłaszcza, że włączenie go jest proste i zgodne z regułami zadania)
9. :-1: za niezgodne z regułami zadania wykluczenie - tak, to podwójny minus na wykluczeniu, jeden za niezgodność w klasie (wykluczony czy nie?) drugi za niedotrzymanie kontraktu (zadanie mówiło przedział obustronnie domknięty).

**Comment by pi0trk** [comment]
Exception name corrected/redundant occurrences removed. ceiling included in drawRandomNumber.
String.format used. Comments removed.
